#!/usr/bin/env bash
# shellcheck disable=SC1090

# set -eo pipefail

function usage() {
  cat <<- EOF

  push all docker images

  usage: $0

EOF
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/../lib/bashui.sh"

get_platform

for D in *; do
  if [ -d "$D" ]; then
    if [ -f "$D/Makefile" ]; then
      action "build $D"
      (cd "$D" && make docker-push)
    fi
  fi
done
